
# =======================
# Server Configuration
# =======================
server:
  shutdown: graceful
  forward-headers-strategy: framework
  servlet:
    context-path: /accountmanaging
  max-http-request-header-size: 128KB

# =======================
# SpringDoc Configuration
# =======================
springdoc:
  swagger-ui:
    # disable-swagger-default-url: true
    path: /swagger-ui.html

# =======================
# plsql Configuration
# =======================
plsql:
  app-key: ACC
  plsql-error-format: true
  region: boae
  suffix: ""
  app-name: app
  logging:
    activity:
      enabled: true
    trace-context:
      enabled: true
    system: Cuentas Vista y Plazo
    subsystem: ISL00140 CUENTAS PERSONALES
    application: 00000148 accountmanaging
    subapplication: accountmanaging
    paas-app-version: "@project.version@"
    functional:
      logged-endpoints: ${server.servlet.context-path}/**
  security:
    connectors:
      pkm-connector:
        pkm-endpoint:
          - https://pkm-gravityplus.fcmech.dev.corp/v1/publicKey
    white-list:
      - /actuator/health/**
      - /**
  core:
    exceptions:
      error-format: extended-error
    reactor:
      context-propagation: AUTO
  cache:          
    caffeine:
      allow-null-values: false
      # disable null values in cache for performance reasons

# =======================
# Spring Configuration
# =======================
spring:
#  config:
#    import: optional:configserver:
  application:
    name: fcm-app-accountmanaging
  session:
    store-type: none
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=5m
  lifecycle.timeout-per-shutdown-phase: 2m
  datasource:
    url: jdbc:oracle:thin:@ODISLM4C.proj.DEV.CORP:60137/ODISLM4C
    jdbcUrl: jdbc:oracle:thin:@ODISLM4C.proj.DEV.CORP:60137/ODISLM4C
    username: DELM4C
    password: ous_C5sT3
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
      connection-test-query: SELECT 1 FROM DUAL
# =======================
# Management Configuration
# =======================
management:
  endpoint:
    health:
      show-details: ALWAYS

# =======================
# Logging Configuration
# =======================
logging:
  level:
    com.java.developing.accounts: INFO
    root: WARN

# =======================
# Resilience4j Configuration
# =======================
resilience4j:
  circuitbreaker:
    configs:
      default:
        minimumNumberOfCalls: 100
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 60000
        failureRateThreshold: 50
        ignore-exceptions:
          - com.java.developing.accounts.util.lib.core.exceptions.BadRequestplsqlExceptionproject
          - com.java.developing.accounts.util.lib.core.exceptions.UnauthorizedplsqlExceptionproject
          - com.java.developing.accounts.util.lib.core.exceptions.ForbiddenplsqlExceptionproject
          - com.java.developing.accounts.util.lib.core.exceptions.NotFoundplsqlExceptionproject
